CREATE TABLE T_USUARIO (
    ID_USUARIO NUMBER(10) NOT NULL,
    NOME_USUARIO VARCHAR2(60) NOT NULL,
    DS_EMAIL_USUARIO VARCHAR2(319),

    CONSTRAINT PK_T_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE T_CONTA_BANCARIA (
    ID_CONTA NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10) NOT NULL,
    CD_BANCO NUMBER(10) NOT NULL,
    NR_VALOR_SALDO NUMBER(8, 2) NOT NULL,
    CD_TIPO_CONTA NUMBER(10) NOT NULL,
    NR_LIMITE_CREDITO NUMBER(8, 2) NOT NULL,

    CONSTRAINT PK_T_CONTA_BANCARIA PRIMARY KEY (ID_CONTA)
);

CREATE TABLE T_FATURA_CARTAO (
    ID_FATURA NUMBER(10) NOT NULL,
    ID_CONTA NUMBER(10) NOT NULL,
    NR_VALOR_FATURA NUMBER(8, 2) NOT NULL,
    NR_MES_FATURA NUMBER(10) NOT NULL,
    DT_ANO_FATURA DATE NOT NULL,
    DT_FECHAMENTO_FATURA DATE NOT NULL,

    CONSTRAINT PK_T_FATURA_CARTAO PRIMARY KEY (ID_FATURA)
);

CREATE TABLE T_TRANSACAO (
    ID_TRANSACAO NUMBER(10) NOT NULL,
    ID_CONTA NUMBER(10) NOT NULL,
    NR_VALOR NUMBER(8, 2) NOT NULL,
    NOME_TRANSACAO VARCHAR2(60) NOT NULL,
    DT_OCORRENCIA TIMESTAMP NOT NULL,
    NR_PERIODICIDADE NUMBER(10) NOT NULL,
    CD_RECEITA_OU_DEBITO NUMBER(1) NOT NULL,
    CD_TIPO NUMBER(10),

    CONSTRAINT PK_T_TRANSACAO PRIMARY KEY (ID_TRANSACAO)
);

CREATE TABLE T_LANCAMENTO (
    ID_LANCAMENTO NUMBER(10) NOT NULL,
    ID_FATURA NUMBER(10) NOT NULL,
    NOME_LANCAMENTO VARCHAR2(60) NOT NULL,
    NR_VALOR_LANCAMENTO NUMBER(8, 2) NOT NULL,
    DS_PERIODICIDADE NUMBER(10) NOT NULL,
    CD_PAGAMENTO_OU_ESTORNO NUMBER(1) NOT NULL,
    DT_OCORRENCIA TIMESTAMP NOT NULL,
    CD_TIPO NUMBER(10),

    CONSTRAINT PK_T_LANCAMENTO PRIMARY KEY (ID_LANCAMENTO)
);

ALTER TABLE T_CONTA_BANCARIA
    ADD CONSTRAINT T_CONTA_T_USUARIO_FK
    FOREIGN KEY (ID_USUARIO)
    REFERENCES T_USUARIO (ID_USUARIO);

ALTER TABLE T_FATURA_CARTAO
    ADD CONSTRAINT T_FATURA_T_CONTA_FK
    FOREIGN KEY (ID_CONTA)
    REFERENCES T_CONTA_BANCARIA (ID_CONTA);

ALTER TABLE T_TRANSACAO
    ADD CONSTRAINT T_TRANSACAO_T_CONTA_FK
    FOREIGN KEY (ID_CONTA)
    REFERENCES T_CONTA_BANCARIA (ID_CONTA);

ALTER TABLE T_LANCAMENTO
    ADD CONSTRAINT T_LANCAMENTO_T_FATURA_FK
    FOREIGN KEY (ID_FATURA)
    REFERENCES T_FATURA_CARTAO (ID_FATURA);

/*

CADASTRO E ALTERAÇÃO

*/

-- Cadastrar um usuário
INSERT INTO T_USUARIO (ID_USUARIO, NOME_USUARIO, DS_EMAIL_USUARIO)
VALUES (1, 'Nome do Usuário', 'usuario@email.com');

-- Cadastrar a conta do usuário
INSERT INTO T_CONTA_BANCARIA (ID_CONTA, ID_USUARIO, CD_BANCO, NR_VALOR_SALDO, CD_TIPO_CONTA, NR_LIMITE_CREDITO)
VALUES (1, 1, 1, 100.00, 1, 200.00);

-- Alterar todos os dados do usuário, utilizando seu código como referência.
UPDATE T_USUARIO
SET NOME_USUARIO = 'Novo Nome',
DS_EMAIL_USUARIO = 'novousuario@email.com'
WHERE ID_USUARIO = 1;

-- Cadastrar as receitas do usuário.
INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (1, 1, 1000.00, 'Salário', TO_TIMESTAMP('2023-10-05 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 12, 1, 1);

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (2, 1, 200.00, 'Rendimentos', TO_TIMESTAMP('2023-10-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 12, 1, 2);

-- Alterar todos os dados das receitas do usuário, utilizando o código como referência.
UPDATE T_TRANSACAO
SET NR_VALOR = 1200.00,
    NOME_TRANSACAO = 'Novo Salário',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-06 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 24,
    CD_RECEITA_OU_DEBITO = 0, -- 0 representa falso (false)
    CD_TIPO = '003'
WHERE ID_TRANSACAO = 1 AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 250.00,
    NOME_TRANSACAO = 'Novos Rendimentos',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-11 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 36,
    CD_RECEITA_OU_DEBITO = 0, -- 0 representa falso (false)
    CD_TIPO = '004'
WHERE ID_TRANSACAO = 2 AND ID_CONTA = 1;

-- Cadastrar as despesas do usuário.
INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (3, 1, 85.00, 'Conta de Luz', TO_TIMESTAMP('2023-10-12 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '005');

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (4, 1, 67.50, 'Conta de Água', TO_TIMESTAMP('2023-10-13 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '006');

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (5, 1, 55.00, 'Internet', TO_TIMESTAMP('2023-10-14 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '007');

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (6, 1, 800.00, 'Aluguel', TO_TIMESTAMP('2023-10-15 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '008');

-- Alterar todos os dados das despesas do usuário, utilizando o código como referência.
UPDATE T_TRANSACAO
SET NR_VALOR = 90.00,
    NOME_TRANSACAO = 'Nova Conta de Luz',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-16 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 2
WHERE CD_TIPO = '005' AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 70.00,
    NOME_TRANSACAO = 'Nova Conta de Água',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-17 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 3
WHERE CD_TIPO = '006' AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 60.00,
    NOME_TRANSACAO = 'Nova Internet',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-18 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 4
WHERE CD_TIPO = '007' AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 850.00,
    NOME_TRANSACAO = 'Novo Aluguel',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-19 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 5
WHERE CD_TIPO = '008' AND ID_CONTA = 1;

-- Cadastrar os dados para investimentos.
/*
    Minha ideia é que os investimentos sejam um lançamento feito dentro de uma conta que seja do 'tipo' investimentos. Para isso, portanto:
    1 - precisamos criar uma nova conta do tipo investimento;
    2 - precisamos adicionar um investimento nessa conta, que será uma transacao, em que é debitado um valor de uma conta corrente, para virar um crédito na conta investimento;
*/

-- Criação da conta de investimento
INSERT INTO T_CONTA_BANCARIA (ID_CONTA, ID_USUARIO, CD_BANCO, NR_VALOR_SALDO, CD_TIPO_CONTA, NR_LIMITE_CREDITO)
VALUES (2, 1, 1, 200.00, 2, 0.00);

-- Débito do valor investido da conta corrente
INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (7, 1, 100.00, 'Investimento 1', TO_TIMESTAMP('2023-10-20 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '009');

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (8, 1, 200.00, 'Investimento 2', TO_TIMESTAMP('2023-10-21 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, '009');

-- Crédito do valor investido na conta de investimento
INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (9, 2, 100.00, 'Investimento 1', TO_TIMESTAMP('2023-10-22 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, '009');

INSERT INTO T_TRANSACAO (ID_TRANSACAO, ID_CONTA, NR_VALOR, NOME_TRANSACAO, DT_OCORRENCIA, NR_PERIODICIDADE, CD_RECEITA_OU_DEBITO, CD_TIPO)
VALUES (10, 2, 200.00, 'Investimento 2', TO_TIMESTAMP('2023-10-23 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, '009');

-- Alterar todos os dados para investimentos do usuário, utilizando o código como referência.
-- Atualizei o débito feito na conta corrente e o crédito correspondente feito na conta de investimento
UPDATE T_TRANSACAO
SET NR_VALOR = 150.00,
    NOME_TRANSACAO = 'Novo Investimento 1',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-24 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 1
WHERE ID_TRANSACAO = 7 AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 150.00,
    NOME_TRANSACAO = 'Novo Investimento 1',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-25 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 1
WHERE ID_TRANSACAO = 8 AND ID_CONTA = 2;

UPDATE T_TRANSACAO
SET NR_VALOR = 250.00,
    NOME_TRANSACAO = 'Novo Investimento 2',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-26 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 1
WHERE ID_TRANSACAO = 9 AND ID_CONTA = 1;

UPDATE T_TRANSACAO
SET NR_VALOR = 250.00,
    NOME_TRANSACAO = 'Novo Investimento 2',
    DT_OCORRENCIA = TO_TIMESTAMP('2023-10-27 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    NR_PERIODICIDADE = 1
WHERE ID_TRANSACAO = 10 AND ID_CONTA = 2;

/*

CONSULTAS

*/

-- Consultar os dados de um usuário (filtrar a partir do seu código).
SELECT *
FROM T_USUARIO
WHERE ID_USUARIO = 1;

-- Consultar os dados de um único registro de despesa de um  usuário (filtrar a partir do código do usuário e do código da despesa).
SELECT *
FROM T_TRANSACAO
WHERE ID_CONTA IN (SELECT ID_CONTA FROM T_CONTA_BANCARIA WHERE ID_USUARIO = 1)
AND CD_TIPO = '005' -- Substitua '005' pelo código da despesa desejada
AND CD_RECEITA_OU_DEBITO = 0 -- 0 representa "false"
AND ROWNUM = 1;

-- Consultar os dados de todos os registros de despesas de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT *
FROM T_TRANSACAO
WHERE ID_CONTA IN (SELECT ID_CONTA FROM T_CONTA_BANCARIA WHERE ID_USUARIO = 1)
AND CD_RECEITA_OU_DEBITO = 0 -- 0 representa "false"
AND CD_TIPO = '005' -- Substitua '005' pelo código da despesa desejada
ORDER BY DT_OCORRENCIA DESC;

-- Consultar os dados de um único registro de investimento de um  usuário (filtrar a partir do código do usuário e do código de investimento).
SELECT *
FROM T_TRANSACAO
WHERE ID_CONTA IN (SELECT ID_CONTA FROM T_CONTA_BANCARIA WHERE ID_USUARIO = 1)
AND CD_TIPO = '009' -- Substitua '009' pelo código de investimento desejado
AND ROWNUM = 1;

-- Consultar os dados de todos os registros de investimentos de um  usuário, ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu código).
SELECT *
FROM T_TRANSACAO
WHERE ID_CONTA IN (SELECT ID_CONTA FROM T_CONTA_BANCARIA WHERE ID_USUARIO = 1)
AND CD_TIPO = '009' -- Substitua '009' pelo código de investimento desejado
ORDER BY DT_OCORRENCIA DESC;

-- Consultar os dados básicos de um usuário, o último investimento registrado e a última despesa registrada (filtrar a partir do código de usuário – consulta necessária para o dashboard. Dica: veja consulta com junções).
SELECT U.*,
(SELECT T.NR_VALOR FROM T_TRANSACAO T WHERE T.DT_OCORRENCIA = (SELECT MAX(DT_OCORRENCIA) FROM T_TRANSACAO WHERE CD_TIPO = 9)) ULTIMO_INVESTIMENTO, 
(SELECT T.NR_VALOR FROM T_TRANSACAO T WHERE T.DT_OCORRENCIA = (SELECT MAX(DT_OCORRENCIA) FROM T_TRANSACAO WHERE CD_TIPO != 9)) ULTIMA_DESPESA
FROM T_USUARIO U
WHERE ID_USUARIO = 1